Repository galaxyproject/tools-iuc, pull requests merged in 2018-06, with the labels that each got.

#1922 Explicitly cast BamTools Filter's rules param to a string
  tool_collections/bamtools/bamtools_filter/bamtools-filter.xml
Labels: affects Main, bug

#1927 Bowtie2 properly set dbkey on outputs
  tools/bowtie2/bowtie2_macros.xml
  tools/bowtie2/bowtie2_wrapper.xml
Labels: affects Main, bug, enhancement

#1929 STAR properly set dbkey on outputs
  tools/rgrnastar/macros.xml
  tools/rgrnastar/rg_rnaStar.xml
Labels: affects Main, bug, enhancement

#1426 Add ggplot2 pca tool
  tools/ggplot2/ggplot2_heatmap.xml
  tools/ggplot2/ggplot2_pca.xml
  tools/ggplot2/ggplot_histogram.xml
  tools/ggplot2/ggplot_point.xml
  tools/ggplot2/ggplot_violin.xml
  tools/ggplot2/heatmap2.xml
  tools/ggplot2/macros.xml
  tools/ggplot2/test-data/ggplot_heatmap_result1.pdf
  tools/ggplot2/test-data/ggplot_pca_result1.pdf
  tools/ggplot2/test-data/mtcars.txt
Labels: new software, reviewer needed
