Repository galaxyproject/tools-iuc, pull requests merged in 2018-03, with the labels that each got.

#1749 fixed input datatypes for lastz
  tools/lastz/lastz.xml
  tools/lastz/lastz_d.xml
  tools/lastz/lastz_macros.xml
Labels: affects Main, bug

#1695 Add R-based charts tool
  tools/charts/.shed.yml
  tools/charts/boxplot.r
  tools/charts/charts.r
  tools/charts/charts.xml
  tools/charts/heatmap.r
  tools/charts/histogram.r
  tools/charts/histogramdiscrete.r
  tools/charts/test-data/boxplot.000.txt
  tools/charts/test-data/boxplot.001.txt
  tools/charts/test-data/heatmap.000.txt
  tools/charts/test-data/histogram.000.txt
  tools/charts/test-data/histogram.001.txt
  tools/charts/test-data/histogram.002.txt
  tools/charts/test-data/histogram.003.txt
  tools/charts/test-data/histogramdiscrete.000.txt
  tools/charts/test-data/tabular.txt
  tools/charts/test-data/tabular_matrix.txt
  tools/charts/test-data/tabular_single.txt
  tools/charts/test-data/tabular_small.txt
Labels: wip

#1791 Separate vcffilter filters into repeats
  tool_collections/vcflib/vcffilter/vcffilter.xml
Labels: bug, high priority

#1784 Use version compatible with packaging.version
  tool_collections/vcflib/vcf2tsv/vcf2tsv.xml
  tool_collections/vcflib/vcfaddinfo/vcfaddinfo.xml
  tool_collections/vcflib/vcfallelicprimitives/vcfallelicprimitives.xml
  tool_collections/vcflib/vcfannotate/vcfannotate.xml
  tool_collections/vcflib/vcfannotategenotypes/vcfannotategenotypes.xml
  tool_collections/vcflib/vcfbedintersect/vcfbedintersect.xml
  tool_collections/vcflib/vcfbreakcreatemulti/vcfbreakcreatemulti.xml
  tool_collections/vcflib/vcfcheck/vcfcheck.xml
  tool_collections/vcflib/vcfcombine/vcfcombine.xml
  tool_collections/vcflib/vcfcommonsamples/vcfcommonsamples.xml
  tool_collections/vcflib/vcfdistance/vcfdistance.xml
  tool_collections/vcflib/vcffixup/vcffixup.xml
  tool_collections/vcflib/vcfflatten/vcfflatten.xml
  tool_collections/vcflib/vcfgeno2haplo/vcfgeno2haplo.xml
  tool_collections/vcflib/vcfgenotypes/vcfgenotypes.xml
  tool_collections/vcflib/vcfhethom/vcfhethom.xml
  tool_collections/vcflib/vcfleftalign/vcfleftalign.xml
  tool_collections/vcflib/vcfprimers/vcfprimers.xml
  tool_collections/vcflib/vcfrandomsample/vcfrandomsample.xml
  tool_collections/vcflib/vcfsort/vcfsort.xml
  tool_collections/vcflib/vcfvcfintersect/vcfvcfintersect.xml
Labels: affects Main, bug

#1787 snpEff rewrite
  tool_collections/snpeff/gbk2fa.py
  tool_collections/snpeff/snpEff.xml
  tool_collections/snpeff/snpEff_create_db.xml
  tool_collections/snpeff/snpEff_databases.xml
  tool_collections/snpeff/snpEff_download.xml
  tool_collections/snpeff/snpEff_macros.xml
  tool_collections/snpeff/test-data/input.gbk
  tool_collections/snpeff/test-data/input.gbk.gz
  tool_collections/snpeff/test-data/output_nover.fna
  tool_collections/snpeff/test-data/output_ver.fna
  tool_collections/snpeff/test-data/pBR322.fna
  tool_collections/snpeff/test-data/pBR322.gbk
Labels: enhancement, high priority
