Repository galaxyproject/tools-iuc, pull requests merged in 2019-08, with the labels that each got.

#2537 Wrapper for pipelign version 0.2
  tools/pipelign/.shed.yml
  tools/pipelign/pipelign.xml
  tools/pipelign/test-data/pipelign-in1.fasta
Labels: new software, reviewer needed

#2548 Fix to Table Compute tool
  tools/table_compute/scripts/safety.py
  tools/table_compute/scripts/table_compute.py
  tools/table_compute/table_compute.xml
  tools/table_compute/test-data/skiplines.tsv
Labels: wip

#2558 Bump STAR to 2.7.2b
  tools/rgrnastar/macros.xml
  tools/rgrnastar/rg_rnaStarSolo.xml
Labels: enhancement
