Repository galaxyproject/tools-iuc, pull requests merged in 2020-06, with the labels that each got.

#3059 Fix prokka output format of genbank dataset
  tools/prokka/prokka.xml
Labels: enhancement

#3075 Add DOI to Circos now that it is published
  tools/circos/karyotype-from-fasta.py
  tools/circos/karyotype-from-lengths.py
  tools/circos/macros.xml
Labels: documentation, enhancement

#3097 Add data manager for the `indexed_maf_files` data table.
  data_managers/data_manager_fetch_index_maf/.shed.yml
  data_managers/data_manager_fetch_index_maf/README
  data_managers/data_manager_fetch_index_maf/data_manager/data_manager_fetch_and_index_maf.py
  data_managers/data_manager_fetch_index_maf/data_manager/data_manager_fetch_and_index_maf.xml
  data_managers/data_manager_fetch_index_maf/data_manager_conf.xml
  data_managers/data_manager_fetch_index_maf/tool-data/maf_index.loc.sample
  data_managers/data_manager_fetch_index_maf/tool_data_table_conf.xml.sample
Labels: new software, reviewer needed

#2306 Fix Target attribute output
  tools/progressivemauve/test-data/1.gff3
  tools/progressivemauve/xmfa2gff3.py
  tools/progressivemauve/xmfa2gff3.xml
Labels: wip
