Repository galaxyproject/tools-iuc, pull requests merged in 2020-11, with the labels that each got.

#3149 tradis essentiality fix?
  tool_collections/biotradis/bacteria_tradis.xml
  tool_collections/biotradis/tradis_essentiality.xml
  tool_collections/biotradis/tradis_gene_insert_sites.xml
Labels: bug

#3278 WIP - IDR add option to connect to private omero instance
  tools/idr_download/README.md
  tools/idr_download/idr_download_by_ids.py
  tools/idr_download/idr_download_by_ids.xml
  tools/idr_download/test-data/test0.tiff
Labels: enhancement

#3264 Remove filter from MAF data table references.
  tools/genebed_maf_to_fasta/genebed_maf_to_fasta.xml
  tools/genebed_maf_to_fasta/macros.xml
  tools/interval2maf/interval2maf.xml
  tools/interval2maf/macros.xml
  tools/maf_stats/maf_stats.xml
Labels: enhancement, reviewer needed

#3292 remove ci_skip note from README
  README.md
Labels: documentation

#3287 Add LUMPY
  tools/lumpy_sv/.shed.yml
  tools/lumpy_sv/lumpy_preprocessing.xml
  tools/lumpy_sv/lumpy_sv.xml
  tools/lumpy_sv/macros.xml
  tools/lumpy_sv/test-data/blasted.bam
  tools/lumpy_sv/test-data/discordants.bam
  tools/lumpy_sv/test-data/sample.bam
  tools/lumpy_sv/test-data/sample.vcf
  tools/lumpy_sv/test-data/splitters.bam
Labels: new software

#3276 Make last train -E optional
  tools/last/lasttrain.xml
  tools/last/test-data/last_train.txt
  tools/last/test-data/last_train_E.txt
Labels: enhancement

#3306 Pass the calculated number of chunks to planemo
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
Labels: bug

#3311 diffbind
  .tt_skip
  tools/diffbind/diffbind.R
  tools/diffbind/diffbind.xml
Labels: wip

#3316 Topic/fix raven test
  tools/raven/.shed.yml
  tools/raven/raven.xml
Labels: bug

#3315 meme, vg_convert: fix openmpi/xg error by setting TMPDIR
  .tt_skip
  tools/meme/meme.xml
  tools/raven/raven.xml
  tools/vg/convert.xml
Labels: bug

#3309 Issue 3297
  tools/ggplot2/macros.xml
Labels: enhancement

#3305 multiqc: plot output seems only available with --flat
  tools/multiqc/multiqc.xml
  tools/multiqc/test-data/pre_alignment_soft_log.txt
Labels: enhancement

#3314 migmap: demonstrate fix by adding java 8
  .tt_skip
  tools/migmap/migmap.xml
Labels: bug

#3321 emboss: properly sanitize regex
  tools/emboss_5/emboss_dreg.xml
  tools/emboss_5/emboss_format_corrector.py
  tools/emboss_5/emboss_preg.xml
  tools/emboss_5/macros.xml
  tools/emboss_5/test-data/dreg.seqtable
  tools/emboss_5/test-data/preg.seqtable
Labels: bug

#3335 data manager mitos: fixed refseq39 reference data
  data_managers/data_manager_mitos/data_manager/data_manager.py
  data_managers/data_manager_mitos/data_manager/data_manager_mitos.xml
  data_managers/data_manager_mitos/test-data/mitos2_refseq63.json
Labels: bug

#3338 Update kraken2 wrapper and data manager to version 2.1.1
  .github/workflows/pr.yaml
  data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.py
  data_managers/data_manager_build_kraken2_database/data_manager/kraken2_build_database.xml
  tool_collections/kraken2/kraken2/kraken2.xml
  tool_collections/kraken2/macros.xml
Labels: bug

#3336 Missing comma in make.contigs.xml
  tools/mothur/make.contigs.xml
Labels: bug

#3346 hisat2: Fix for issue #3312, an update to square root symbol in function arguments
  tools/hisat2/hisat2.xml
  tools/hisat2/hisat2_macros.xml
Labels: enhancement, paper-cut

#3350 Adding the tool GECKO
  tools/gecko/.shed.yml
  tools/gecko/README.md
  tools/gecko/gecko.xml
  tools/gecko/test-data/flocculare_16S.fasta
  tools/gecko/test-data/hyopneumoniae_16S-flocculare_16S.csv
  tools/gecko/test-data/hyopneumoniae_16S-flocculare_16S.txt
  tools/gecko/test-data/hyopneumoniae_16S.fasta
Labels: new software

#3283 Adding flair wrapper
  tools/flair/.shed.yml
  tools/flair/flair_collapse.xml
  tools/flair/flair_correct.xml
  tools/flair/flair_macros.xml
  tools/flair/test-data/UCSC_Main_on_Human_knownGene_region_chrM.gtf
  tools/flair/test-data/chrM.bed12
  tools/flair/test-data/chrM.fa
  tools/flair/test-data/chrM.fa.fai
  tools/flair/test-data/chrM.fastq.gz
  tools/flair/test-data/fasta_indexes.loc
  tools/flair/test-data/flair.collapse.isoforms.bed
  tools/flair/test-data/flair.collapse.isoforms.fa
  tools/flair/test-data/flair.collapse.isoforms.gtf
  tools/flair/test-data/flair_all_corrected.bed
  tools/flair/test-data/flair_all_inconsistent.bed
  tools/flair/tool-data/fasta_indexes.loc.sample
  tools/flair/tool_data_table_conf.xml.sample
  tools/flair/tool_data_table_conf.xml.test
Labels: new software, wip

#3071 starting with ena_upload_cli wrapper
  tools/ena_upload/.shed.yml
  tools/ena_upload/README.md
  tools/ena_upload/ena_upload.xml
  tools/ena_upload/extract_tables.py
  tools/ena_upload/process_xlsx.py
  tools/ena_upload/samples_macros.xml
  tools/ena_upload/test-data/1.fastqsanger.gz
  tools/ena_upload/test-data/metadata_test_nonviral.xlsx
  tools/ena_upload/test-data/metadata_test_viral.xlsx
  tools/ena_upload/test-data/sample.fq
  tools/ena_upload/tool-data/geographic_location_1.loc.sample
  tools/ena_upload/tool-data/host_health_state_1.loc.sample
  tools/ena_upload/tool-data/host_sex_1.loc.sample
  tools/ena_upload/tool-data/instrument_model.loc.sample
  tools/ena_upload/tool-data/library_layout.loc.sample
  tools/ena_upload/tool-data/library_selection.loc.sample
  tools/ena_upload/tool-data/library_source.loc.sample
  tools/ena_upload/tool-data/library_strategy.loc.sample
  tools/ena_upload/tool-data/study_type.loc.sample
  tools/ena_upload/tool_data_table_conf.xml.sample
  tools/ena_upload/tool_data_table_conf.xml.test
Labels: new software

#3354 Adding SpyBOAT tool
  tools/spyboat/.shed.yml
  tools/spyboat/output_report.py
  tools/spyboat/run_tests.sh
  tools/spyboat/spyboat.xml
  tools/spyboat/spyboat_cli.py
  tools/spyboat/test-data/output1.html
  tools/spyboat/test-data/test-movie.tif
Labels: new software
