Repository galaxyproject/tools-iuc, pull requests merged in 2020-09, with the labels that each got.

#3184 Set the number of megahit threads in Galaxy server
  tools/megahit/megahit_wrapper.xml
Labels: enhancement

#3194 fix codeml tests
  tools/codeml/codeml.xml
  tools/codeml/test-data/1_run_codeml
  tools/codeml/test-data/2_run_codeml
  tools/codeml/test-data/3_run_codeml
  tools/codeml/test-data/empty
Labels: bug

#3197 fix links in mothur data manager
  data_managers/data_manager_mothur_toolsuite/data_manager/data_manager_fetch_mothur_reference_data.xml
  data_managers/data_manager_mothur_toolsuite/data_manager/fetch_mothur_reference_data.py
Labels: bug

#3198 fix tests for structureharvester
  tools/structureharvester/structureharvester.xml
  tools/structureharvester/test-data/clumpp_indfile/K1.indfile
  tools/structureharvester/test-data/clumpp_indfile/K2.indfile
  tools/structureharvester/test-data/clumpp_indfile/K3.indfile
  tools/structureharvester/test-data/clumpp_indfile/K4.indfile
  tools/structureharvester/test-data/clumpp_popfile/K1.popfile
  tools/structureharvester/test-data/clumpp_popfile/K2.popfile
  tools/structureharvester/test-data/clumpp_popfile/K3.popfile
  tools/structureharvester/test-data/clumpp_popfile/K4.popfile
Labels: bug

#3199 Add support for multiple nucleotide substitions to HyPhy-aBSREL.
  tools/hyphy/hyphy_absrel.xml
  tools/hyphy/test-data/absrel-out1.json
Labels: enhancement

#3172 ncbi_entrez_eutils Addresses 1 minor bug and adds a lot of input/output functionality
  tools/ncbi_entrez_eutils/__efetch_build_options.py
  tools/ncbi_entrez_eutils/ecitmatch.py
  tools/ncbi_entrez_eutils/efetch.py
  tools/ncbi_entrez_eutils/efetch.xml
  tools/ncbi_entrez_eutils/egquery.py
  tools/ncbi_entrez_eutils/egquery.xml
  tools/ncbi_entrez_eutils/einfo.py
  tools/ncbi_entrez_eutils/einfo.xml
  tools/ncbi_entrez_eutils/elink.py
  tools/ncbi_entrez_eutils/elink.xml
  tools/ncbi_entrez_eutils/epost.py
  tools/ncbi_entrez_eutils/epost.xml
  tools/ncbi_entrez_eutils/esearch.py
  tools/ncbi_entrez_eutils/esearch.xml
  tools/ncbi_entrez_eutils/esummary.py
  tools/ncbi_entrez_eutils/esummary.xml
  tools/ncbi_entrez_eutils/eutils.py
  tools/ncbi_entrez_eutils/generate_macros_xml.pl
  tools/ncbi_entrez_eutils/macros.xml
  tools/ncbi_entrez_eutils/test-data/efetchin.tabular
  tools/ncbi_entrez_eutils/test-data/einfo.dblist.xml
  tools/ncbi_entrez_eutils/test-data/elink.elinkin_1link.json
  tools/ncbi_entrez_eutils/test-data/elink.elinkin_1link_hist.json
  tools/ncbi_entrez_eutils/test-data/elink.elinkin_1link_id.tabular
  tools/ncbi_entrez_eutils/test-data/elink.elinkin_allalllinks_id.xml
  tools/ncbi_entrez_eutils/test-data/elink.elinkin_alllinks_id.xml
  tools/ncbi_entrez_eutils/test-data/elink.esearch_in_xmlid.xml
  tools/ncbi_entrez_eutils/test-data/elink.esearch_in_xmlid_1link.tabular
  tools/ncbi_entrez_eutils/test-data/elink.esearchin_id.json
  tools/ncbi_entrez_eutils/test-data/elink.esearchin_id.tabular
  tools/ncbi_entrez_eutils/test-data/elink.esearchin_id_1link.xml
  tools/ncbi_entrez_eutils/test-data/elink.esearchin_id_alllinks.json
  tools/ncbi_entrez_eutils/test-data/esearch.gene.hist.json
  tools/ncbi_entrez_eutils/test-data/esearch.gene.hist.xml
  tools/ncbi_entrez_eutils/test-data/esearch.gene.json
  tools/ncbi_entrez_eutils/test-data/esearch.gene.tabular
  tools/ncbi_entrez_eutils/test-data/esearch.gene.xml
Labels: enhancement

#3139 Add wrapper for delly suite
  tools/delly/.shed.yml
  tools/delly/call.xml
  tools/delly/filter.xml
  tools/delly/lr.xml
  tools/delly/macros.xml
  tools/delly/merge.xml
  tools/delly/test-data/call_1.bcf.gz
  tools/delly/test-data/call_1.vcf.gz
  tools/delly/test-data/call_2.bcf.gz
  tools/delly/test-data/call_2.vcf.gz
  tools/delly/test-data/exclude.tsv
  tools/delly/test-data/genome.fasta
  tools/delly/test-data/normal.bam
  tools/delly/test-data/samples.tsv
  tools/delly/test-data/tumor.bam
Labels: new software
