Repository galaxyproject/tools-iuc, pull requests merged in 2020-04, with the labels that each got.

#2948 Add parameter to IQ-TREE wrapper for short alignments
  tools/iqtree/iqtree.xml
  tools/iqtree/test-data/short.fasta
Labels: affects UseGalaxy.*, bug, enhancement, reviewer needed

#2960 Add minimal wrapper for minia
  tools/minia/.shed.yml
  tools/minia/minia.xml
  tools/minia/test-data/ec.fa
  tools/odgi/build.xml
  tools/odgi/vis.xml
Labels: new software

#2977 Update HyPhy to 2.5.9
  tools/hyphy/hyphy_busted.xml
  tools/hyphy/hyphy_prime.xml
  tools/hyphy/hyphy_sm19.xml
  tools/hyphy/macros.xml
Labels: enhancement

#2995 Update to HyPhy 2.5.11
  tools/hyphy/macros.xml
Labels: enhancement

#2999 permit anonymous usage of jbrowse
  tools/jbrowse/jbrowse.xml
  tools/jbrowse/macros.xml
Labels: bug

#3001 Retry fasterq_dump prefetch up to thrice on failure.
  tools/sra-tools/fasterq_dump.xml
  tools/sra-tools/sra_macros.xml
Labels: enhancement
