Repository galaxyproject/tools-iuc, pull requests merged in 2020-12, with the labels that each got.

#3333 Add SNP Frequency Plot
  tools/snpfreqplot/.shed.yml
  tools/snpfreqplot/heatmap_for_variants.R
  tools/snpfreqplot/helperFunctions.R
  tools/snpfreqplot/snpEffExtract.R
  tools/snpfreqplot/snpfreqplot.xml
  tools/snpfreqplot/static/images/example_output.png
  tools/snpfreqplot/test-data/1084592.vcf
  tools/snpfreqplot/test-data/1085080.vcf
  tools/snpfreqplot/test-data/1085445.vcf
  tools/snpfreqplot/test-data/1085841.vcf
  tools/snpfreqplot/test-data/1085990.vcf
  tools/snpfreqplot/test-data/heatmap.clustering2.jpeg
  tools/snpfreqplot/test-data/heatmap.default.pdf
  tools/snpfreqplot/test-data/heatmap.from_vcf.pdf
  tools/snpfreqplot/test-data/heatmap.imageopts.png
  tools/snpfreqplot/test-data/input436.tabular
  tools/snpfreqplot/test-data/input437.tabular
  tools/snpfreqplot/test-data/input438.tabular
  tools/snpfreqplot/test-data/input439.tabular
  tools/snpfreqplot/test-data/input440.tabular
  tools/snpfreqplot/test-data/input441.tabular
  tools/snpfreqplot/test-data/input442.tabular
  tools/snpfreqplot/test-data/input443.tabular
  tools/snpfreqplot/test-data/input444.tabular
  tools/snpfreqplot/test-data/snpeff.123.vcf
  tools/snpfreqplot/test-data/snpeff.456.vcf
  tools/snpfreqplot/test-data/snpeff.789.vcf
Labels: new software

#3289 mothur screen.seqs bugfix
  tools/mothur/screen.seqs.xml
  tools/mothur/test-data/Mock_S280_L001_R1_001_small.trim.contigs.optimize.end.maxambig.bad.accnos
  tools/mothur/test-data/Mock_S280_L001_R1_001_small.trim.contigs.optimize.end.maxambig.good.fasta
  tools/mothur/test-data/Mock_S280_L001_R1_001_small.trim.contigs.optimize.minlength.maxlength.maxhomop.bad.accnos
  tools/mothur/test-data/Mock_S280_L001_R1_001_small.trim.contigs.optimize.minlength.maxlength.maxhomop.good.fasta
Labels: enhancement, missing tests, wip

#3366 hiccorrelate: fix access to range
  tools/hicexplorer/macros.xml
Labels: bug

#3396 Update to HyPhy 2.5.24
  tools/hyphy/macros.xml
Labels: enhancement, reviewer needed

#3383 Update Maker to 2.31.11
  tools/maker/macros.xml
  tools/maker/maker.xml
  tools/maker/test-data/annot_dfam.gff3
  tools/maker/test-data/annot_dfam_up.gff3
  tools/maker/test-data/annot_human.gff3
  tools/maker/test-data/annot_model.gff3
  tools/maker/test-data/annot_repbase.gff3
  tools/maker/test-data/evidences_human.gff3
  tools/maker/test-data/evidences_model.gff3
  tools/maker/test-data/evidences_norm.gff3
  tools/maker/test-data/evidences_norm_dfam_up.gff3
  tools/maker/test-data/evidences_reuse.gff3
Labels: reviewer needed
