Repository galaxyproject/tools-iuc, pull requests merged in 2020-07, with the labels that each got.

#3109 cutadapt: do not ignore maxn for 0 and adapter sanitizer
  tools/cutadapt/cutadapt.xml
  tools/cutadapt/macros.xml
Labels: affects UseGalaxy.*, bug

#3110 Simple table to gff3 conversion
  tools/tbl2gff3/.shed.yml
  tools/tbl2gff3/LICENSE
  tools/tbl2gff3/macros.xml
  tools/tbl2gff3/tbl2gff3.py
  tools/tbl2gff3/tbl2gff3.xml
  tools/tbl2gff3/test-data/blast.gff3
  tools/tbl2gff3/test-data/input.tab
Labels: new software

#3123 Add FASTQE as a Galaxy tool 🎉🔬🦠🧫🧪💉🧬🥳
  tools/fastqe/.shed.yml
  tools/fastqe/fastqe.xml
  tools/fastqe/test-data/out.html
  tools/fastqe/test-data/test.fq
  tools/fastqe/test-data/test2.fq
Labels: new software

#3141 Fastqe: escape element identifier
  tools/fastqe/fastqe.xml
Labels: cofest
