Repository galaxyproject/tools-iuc, pull requests merged in 2021-08, with the labels that each got.

#3871 Update iqtree wrapper to 2.1.2
  tools/iqtree/iqtree.xml
  tools/iqtree/iqtree_macros.xml
Labels: enhancement, reviewer needed

#3864 Instrain Tool integration to Galaxy
  tools/instrain/.shed.yml
  tools/instrain/instrain_compare.xml
  tools/instrain/instrain_profile.xml
  tools/instrain/macros.xml
  tools/instrain/test-data/N5_271_010G1.maxbin2.stb
  tools/instrain/test-data/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS.zip
  tools/instrain/test-data/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS.zip
  tools/instrain/test-data/SmallScaffold.fa
  tools/instrain/test-data/SmallScaffold.fa.sorted.bam
Labels: wip

#3872 Update iqtree wrapper
  tools/iqtree/iqtree.xml
Labels: enhancement, reviewer needed

#3878 Add test for time tree reconstruction, fix multithreading.
  tools/iqtree/iqtree.xml
  tools/iqtree/test-data/dates.fa
  tools/iqtree/test-data/dates.tabular
Labels: enhancement

#3888 Fix iqtree inputs
  tools/iqtree/iqtree.xml
Labels: bug, reviewer needed, affects UseGalaxy.*

#3890 Update iq-tree: Add output and test for LSD report.
  tools/iqtree/iqtree.xml
Labels: enhancement, reviewer needed

#3808 Modify bealign wrapper to support selection analyses
  data_managers/data_manager_selection_background/.shed.yml
  data_managers/data_manager_selection_background/data_manager/data_manager_selection_background.py
  data_managers/data_manager_selection_background/data_manager/data_manager_selection_background.xml
  data_managers/data_manager_selection_background/data_manager_conf.xml
  data_managers/data_manager_selection_background/test-data/selection-in1.fa
  data_managers/data_manager_selection_background/test-data/selection-out1.json
  data_managers/data_manager_selection_background/tool_data_table_conf.xml.sample
  tools/bioext/bam2msa.xml
  tools/bioext/bealign.xml
  tools/bioext/bealign_selection.loc.sample
  tools/bioext/copy_reference.py
  tools/bioext/macros.xml
  tools/bioext/test-data/bam2msa-in1.bam
  tools/bioext/test-data/bam2msa-in2.bam
  tools/bioext/test-data/bealign-in-ref-1.fa
  tools/bioext/test-data/bealign-in-ref-2.fa
  tools/bioext/test-data/bealign-in2.fa
  tools/bioext/test-data/bealign-out1.bam
  tools/bioext/test-data/bealign-out2.bam
  tools/bioext/test-data/bealign-out3-background.bam
  tools/bioext/test-data/bealign-out3.bam
  tools/bioext/test-data/bealign-out4.bam
  tools/bioext/test-data/bealign_selection.loc
  tools/bioext/test-data/nsp8.fa
  tools/bioext/test-data/query.fa
  tools/bioext/test-data/reference.fa
  tools/bioext/tool_data_table_conf.xml
  tools/bioext/tool_data_table_conf.xml.sample
  tools/bioext/tool_data_table_conf.xml.test
Labels: bug, enhancement

#3897 Update selection data manager
  data_managers/data_manager_selection_background/data_manager/data_manager_selection_background.py
  data_managers/data_manager_selection_background/data_manager/data_manager_selection_background.xml
  data_managers/data_manager_selection_background/data_manager_conf.xml
  data_managers/data_manager_selection_background/test-data/selection-out1.json
  data_managers/data_manager_selection_background/tool-data/selection_background.loc.sample
  data_managers/data_manager_selection_background/tool_data_table_conf.xml.sample
Labels: bug, reviewer needed, affects UseGalaxy.*

#3907 fix pangolearn DM tag parsing
  data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.py
  data_managers/data_manager_pangolearn/data_manager/pangolearn_dm.xml
Labels: bug
