Repository galaxyproject/tools-iuc, pull requests merged in 2021-04, with the labels that each got.

#3565 LASTZ: added differences output option. Incremented version
  tools/lastz/lastz.xml
  tools/lastz/lastz_d.xml
  tools/lastz/test-data/test6.out
Labels: enhancement

#3588 Update HyPhy wrappers to 2.5.30
  tools/hyphy/macros.xml
Labels: enhancement, reviewer needed

#3598 Updates to HyPhy wrappers
  tools/hyphy/hyphy_absrel.xml
  tools/hyphy/hyphy_bgm.xml
  tools/hyphy/hyphy_busted.xml
  tools/hyphy/hyphy_fade.xml
  tools/hyphy/hyphy_fel.xml
  tools/hyphy/hyphy_fubar.xml
  tools/hyphy/hyphy_gard.xml
  tools/hyphy/hyphy_meme.xml
  tools/hyphy/hyphy_prime.xml
  tools/hyphy/hyphy_relax.xml
  tools/hyphy/hyphy_slac.xml
  tools/hyphy/hyphy_sm19.xml
  tools/hyphy/macros.xml
  tools/hyphy/test-data/fubar-in1.fa
  tools/hyphy/test-data/fubar-in1.fa.gz
Labels: enhancement

#3611 Update output datatype for HyPhy-Conv
  tools/hyphy/hyphy_conv.xml
  tools/hyphy/test-data/conv-out1.nex
Labels: bug

#3610 TN-93 updates
  tools/tn93/macros.xml
  tools/tn93/test-data/cluster-in1-1.fa
  tools/tn93/test-data/cluster-in1-2.fa
  tools/tn93/test-data/cluster-out1.fa
  tools/tn93/test-data/cluster-out1.json
  tools/tn93/test-data/filter-in1-clusters.fa
  tools/tn93/test-data/filter-in1-reads.fa
  tools/tn93/test-data/filter-in1-reference.fa
  tools/tn93/test-data/filter-out1.fasta
  tools/tn93/tn93_cluster.py
  tools/tn93/tn93_cluster.xml
  tools/tn93/tn93_filter.py
  tools/tn93/tn93_filter.xml
Labels: enhancement, new software, reviewer needed

#3626 Additional HyPhy updates and bugfixes
  tools/hyphy/hyphy_absrel.xml
  tools/hyphy/hyphy_annotate.xml
  tools/hyphy/hyphy_bgm.xml
  tools/hyphy/hyphy_busted.xml
  tools/hyphy/hyphy_cfel.xml
  tools/hyphy/hyphy_conv.xml
  tools/hyphy/hyphy_fade.xml
  tools/hyphy/hyphy_fel.xml
  tools/hyphy/hyphy_fubar.xml
  tools/hyphy/hyphy_gard.xml
  tools/hyphy/hyphy_meme.xml
  tools/hyphy/hyphy_prime.xml
  tools/hyphy/hyphy_relax.xml
  tools/hyphy/hyphy_slac.xml
  tools/hyphy/hyphy_sm19.xml
  tools/hyphy/macros.xml
  tools/hyphy/test-data/busted-in2.nex
  tools/hyphy/test-data/busted-out1.json
  tools/hyphy/test-data/busted-out2-1.json
  tools/hyphy/test-data/busted-out2-2.json
  tools/hyphy/test-data/gard-out1.json
  tools/hyphy/test-data/gard-out1.nex
  tools/hyphy/test-data/relax-in2.nex
  tools/hyphy/test-data/relax-out1.json
  tools/hyphy/test-data/relax-out2-1.json
  tools/hyphy/test-data/relax-out2-2.json
Labels: enhancement, reviewer needed

#3637 jasminesv: allow gz input
  tools/jasminesv/jasminesv.xml
  tools/jasminesv/macros.xml
  tools/jasminesv/test-data/all_fasta.loc
  tools/jasminesv/test-data/genome.fa
  tools/jasminesv/test-data/genome.fa.gz
Labels: enhancement

#3544 Add wrapper for GenomeScope2
  tools/genomescope/.shed.yml
  tools/genomescope/genomescope.xml
  tools/genomescope/test-data/genomescope-in1.tab
  tools/genomescope/test-data/genomescope-out1-1.png
  tools/genomescope/test-data/genomescope-out1-1.tab
  tools/genomescope/test-data/genomescope-out1-1.txt
  tools/genomescope/test-data/genomescope-out1-2.png
  tools/genomescope/test-data/genomescope-out1-2.txt
  tools/genomescope/test-data/genomescope-out1-3.png
  tools/genomescope/test-data/genomescope-out1-3.txt
  tools/genomescope/test-data/genomescope-out1-4.png
Labels: new software, reviewer needed
