Repository galaxyproject/tools-iuc, pull requests merged in 2021-07, with the labels that each got.

#3775 Fix bug in HyPhy-Summary newick parser, update tests.
  tools/hyphy/hyphy_summary.xml
  tools/hyphy/scripts/hyphy_summary.py
  tools/hyphy/test-data/summary/ORF6-segment.json
  tools/hyphy/test-data/summary/merged-segment.json
  tools/hyphy/test-data/summary/merged-site.json
  tools/hyphy/test-data/summary/nsp7-segment.json
  tools/hyphy/test-data/summary/nsp8-segment.json
  tools/hyphy/test-data/summary/nsp8-site.json
Labels: affects UseGalaxy.*, bug

#3781 fix dropletutils plot
  tools/dropletutils/dropletutils.xml
  tools/dropletutils/scripts/dropletutils.Rscript
  tools/dropletutils/test-data/defs_barcoderankings.png
Labels: bug

#3774 Update bioext to 0.20.1
  tools/bioext/bam2msa.xml
  tools/bioext/bealign.xml
  tools/bioext/macros.xml
  tools/bioext/test-data/bam2msa-out1.fa
  tools/bioext/test-data/bealign-out1.bam
Labels: affects UseGalaxy.*, enhancement, reviewer needed

#3805 Edits for column join help section
  tools/collection_column_join/collection_column_join.xml
Labels: enhancement, wip
