Repository galaxyproject/tools-iuc, pull requests merged in 2021-05, with the labels that each got.

#3640 fix orthofinder
  tools/orthofinder/macros.xml
  tools/orthofinder/orthofinder_only_groups.xml
Labels: bug

#3662 Fix fastq.gz support in Trinity
  tools/trinity/trinity.xml
Labels: bug

#3627 Update bioext tools to 0.19.7 and sanitize input
  tools/bioext/bealign.xml
  tools/bioext/macros.xml
Labels: enhancement, reviewer needed

#3673 Correct output handling for HyPhy-BGM.
  tools/hyphy/hyphy_bgm.xml
Labels: affects UseGalaxy.*, bug, reviewer needed
