Repository galaxyproject/tools-iuc, pull requests merged in 2021-01, with the labels that each got.

#3375 Update samtools_view.xml - use GALAXY_MEMORY_MB_PER_SLOT as samtools_…
  tool_collections/samtools/samtools_view/samtools_view.xml
Labels: enhancement

#3347 data_manager_manual: fix DetachedInstanceError with >20.05
  data_managers/data_manager_manual/data_manager/data_manager_manual.py
Labels: bug, reviewer needed

#3418 Update HyPhy wrappers to 2.5.25
  tools/hyphy/macros.xml
Labels: enhancement, reviewer needed

#3179 Add rgcca
  tools/rgcca/.shed.yml
  tools/rgcca/launcher.R
  tools/rgcca/macro.xml
  tools/rgcca/rgcca.xml
  tools/rgcca/test-data/1block/ave.pdf
  tools/rgcca/test-data/1block/corcircle.pdf
  tools/rgcca/test-data/1block/design.pdf
  tools/rgcca/test-data/1block/individuals.pdf
  tools/rgcca/test-data/1block/rgcca.result.RData
  tools/rgcca/test-data/1block/top_variables.pdf
  tools/rgcca/test-data/2blocks/ave.pdf
  tools/rgcca/test-data/2blocks/corcircle.pdf
  tools/rgcca/test-data/2blocks/design.pdf
  tools/rgcca/test-data/2blocks/individuals.pdf
  tools/rgcca/test-data/2blocks/rgcca.result.RData
  tools/rgcca/test-data/2blocks/top_variables.pdf
  tools/rgcca/test-data/3blocks/ave.pdf
  tools/rgcca/test-data/3blocks/corcircle.pdf
  tools/rgcca/test-data/3blocks/design.pdf
  tools/rgcca/test-data/3blocks/individuals.pdf
  tools/rgcca/test-data/3blocks/rgcca.result.RData
  tools/rgcca/test-data/3blocks/top_variables.pdf
  tools/rgcca/test-data/3blocks_connection/ave.pdf
  tools/rgcca/test-data/3blocks_connection/corcircle.pdf
  tools/rgcca/test-data/3blocks_connection/design.pdf
  tools/rgcca/test-data/3blocks_connection/individuals.pdf
  tools/rgcca/test-data/3blocks_connection/rgcca.result.RData
  tools/rgcca/test-data/3blocks_connection/top_variables.pdf
  tools/rgcca/test-data/3blocks_sgcca/ave.pdf
  tools/rgcca/test-data/3blocks_sgcca/corcircle.pdf
  tools/rgcca/test-data/3blocks_sgcca/design.pdf
  tools/rgcca/test-data/3blocks_sgcca/individuals.pdf
  tools/rgcca/test-data/3blocks_sgcca/rgcca.result.RData
  tools/rgcca/test-data/3blocks_sgcca/top_variables.pdf
  tools/rgcca/test-data/3blocks_supervised/ave.pdf
  tools/rgcca/test-data/3blocks_supervised/corcircle.pdf
  tools/rgcca/test-data/3blocks_supervised/design.pdf
  tools/rgcca/test-data/3blocks_supervised/individuals.pdf
  tools/rgcca/test-data/3blocks_supervised/rgcca.result.RData
  tools/rgcca/test-data/3blocks_supervised/top_variables.pdf
  tools/rgcca/test-data/agriculture.tsv
  tools/rgcca/test-data/connection.tsv
  tools/rgcca/test-data/industry.tsv
  tools/rgcca/test-data/politic.tsv
  tools/rgcca/test-data/political_system.tsv
Labels: new software

#3204 do not use >1 threads for velveth in velveloptimizer
  tools/velvet_optimiser/velvetoptimiser.xml
Labels: bug, enhancement

#3423 hmmer: fix number of CPUs
  tools/hmmer3/hmmbuild.xml
  tools/hmmer3/hmmscan.xml
  tools/hmmer3/hmmsearch.xml
  tools/hmmer3/jackhmmer.xml
  tools/hmmer3/macros.xml
  tools/hmmer3/nhmmer.xml
  tools/hmmer3/nhmmscan.xml
  tools/hmmer3/phmmer.xml
Labels: bug

#3430 Update to HyPhy 2.5.26
  tools/hyphy/macros.xml
Labels: enhancement, reviewer needed

#3427 fix ruvseq
  tools/ruvseq/ruvseq.R
  tools/ruvseq/ruvseq.xml
Labels: bug

#3429 chimera.vsearch: fix output filter
  tools/mothur/chimera.vsearch.xml
  tools/mothur/test-data/chimera.count_table_wogroups
  tools/mothur/test-data/chimera.vsearch.accnos
  tools/mothur/test-data/chimera.vsearch.chimeras_wogroups
Labels: bug
