Repository galaxyproject/tools-iuc, pull requests merged in 2022-04, with the labels that each got.

#4475 Add the magicblast tool
  tools/blast/.shed.yml
  tools/blast/macros.xml
  tools/blast/magicblast.xml
  tools/blast/test-data/blastdb.loc
  tools/blast/test-data/gilist1.tabular
  tools/blast/test-data/phiX174/blastdb.nhd
  tools/blast/test-data/phiX174/blastdb.nhi
  tools/blast/test-data/phiX174/blastdb.nhr
  tools/blast/test-data/phiX174/blastdb.nin
  tools/blast/test-data/phiX174/blastdb.nog
  tools/blast/test-data/phiX174/blastdb.nsd
  tools/blast/test-data/phiX174/blastdb.nsi
  tools/blast/test-data/phiX174/blastdb.nsq
  tools/blast/test-data/query1.fasta.gz
  tools/blast/test-data/query_forward1.fastqsanger.gz
  tools/blast/test-data/query_reverse1.fastqsanger.gz
  tools/blast/test-data/subject1.fasta.gz
  tools/blast/test-data/taxids.tabular
  tools/blast/tool-data/blastdb.loc.sample
  tools/blast/tool_data_table_conf.xml.sample
  tools/blast/tool_data_table_conf.xml.test
Labels: new software

#4489 pathview: fix version token
  tools/pathview/pathview.xml
Labels: bug

#4483 Add nAltORFs
  tools/naltorfs/.shed.yml
  tools/naltorfs/bicodon_counts_from_fasta.xml
  tools/naltorfs/codon_freq_from_bicodons.xml
  tools/naltorfs/find_nested_alt_orfs.xml
  tools/naltorfs/macros.xml
  tools/naltorfs/test-data/aa_freq_from_bicodon.tabular
  tools/naltorfs/test-data/all_fasta.loc
  tools/naltorfs/test-data/bed_out.bed
  tools/naltorfs/test-data/bicodon_out.tabular
  tools/naltorfs/test-data/cds_fasta_out.fasta
  tools/naltorfs/test-data/codon_freq_from_bicodon.tabular
  tools/naltorfs/test-data/codon_freq_from_bicodon_log.txt
  tools/naltorfs/test-data/codon_out.tabular
  tools/naltorfs/test-data/find_naltorfs_log.txt
  tools/naltorfs/test-data/gencode_canonical.hg38.chr6_GL0002508.bed
  tools/naltorfs/test-data/hg38.chr6_GL000250v2_alt.2bit.gz
  tools/naltorfs/test-data/naltorfs_fasta_out.fasta
  tools/naltorfs/test-data/peptide_fasta_out.fasta
  tools/naltorfs/test-data/twobit.loc
  tools/naltorfs/tool-data/all_fasta.loc.sample
  tools/naltorfs/tool-data/twobit.loc.sample
  tools/naltorfs/tool_data_table_conf.xml.sample
  tools/naltorfs/tool_data_table_conf.xml.test
Labels: new software

#4316 Update Stacks2
  tools/stacks2/macros.xml
  tools/stacks2/macros_process.xml
  tools/stacks2/stacks_clonefilter.xml
  tools/stacks2/stacks_cstacks.xml
  tools/stacks2/stacks_denovomap.xml
  tools/stacks2/stacks_gstacks.xml
  tools/stacks2/stacks_kmerfilter.xml
  tools/stacks2/stacks_populations.xml
  tools/stacks2/stacks_procrad.xml
  tools/stacks2/stacks_refmap.xml
  tools/stacks2/stacks_shortreads.xml
  tools/stacks2/stacks_sstacks.xml
  tools/stacks2/stacks_tsv2bam.xml
  tools/stacks2/stacks_ustacks.xml
  tools/stacks2/test-data/demultiplexed/PopA_01.fq
  tools/stacks2/test-data/procrad/R1.fa.discards
  tools/stacks2/test-data/procrad/R1.fq
  tools/stacks2/test-data/procrad/R1.fq.discards
  tools/stacks2/test-data/procrad/R1_01.fq
  tools/stacks2/test-data/procrad/R1_02.fq
  tools/stacks2/test-data/procrad/R1_03.fq
  tools/stacks2/test-data/procrad/R1_04.fq
  tools/stacks2/test-data/procrad/R2.fq
  tools/stacks2/test-data/procrad/R2.fq.discards
  tools/stacks2/test-data/procrad/R2_01.fq
  tools/stacks2/test-data/procrad/R2_02.fq
  tools/stacks2/test-data/procrad/R2_03.fq
  tools/stacks2/test-data/procrad/R2_04.fq
  tools/stacks2/test-data/procrad/process_radtags.out
  tools/stacks2/test-data/procrad/process_radtags2.out
  tools/stacks2/test-data/procrad/process_radtags_paired.out
  tools/stacks2/test-data/procrad/process_radtags_paired_no_barcode.out
  tools/stacks2/test-data/shortreads/PopA_01.fq
  tools/stacks2/test-data/shortreads/process_shortreads.out
Labels: wip

#4458 add new tools dnabot v 3.1.0
  tools/dnabot/.shed.yml
  tools/dnabot/dnabot.xml
  tools/dnabot/static/images/DNABOT_WF.PNG
  tools/dnabot/test-data/constructs.csv
  tools/dnabot/test-data/linker_parts_coords.csv
  tools/dnabot/test-data/user_parts_coords.csv
Labels: new software
