Repository galaxyproject/tools-iuc, pull requests merged in 2022-07, with the labels that each got.

#4659 SPAdes: fix stats Python script
  tools/spades/macros.xml
  tools/spades/metaplasmidspades.xml
  tools/spades/metaviralspades.xml
  tools/spades/plasmidspades.xml
  tools/spades/rnaviralspades.xml
  tools/spades/spades.xml
  tools/spades/write_tsv_script.py
Labels: bug

#4654 Gemini query: fix region filter option
  tools/gemini/gemini_gene_wise.xml
  tools/gemini/gemini_load.xml
  tools/gemini/gemini_macros.xml
  tools/gemini/gemini_query.xml
  tools/gemini/test-data/gemini_region_filter.tabular
Labels: bug

#4663 Tolerate empty lines in ivar helper scripts inputs
  tools/ivar/ivar_removereads.xml
  tools/ivar/ivar_trim.xml
  tools/ivar/prepare_amplicon_info.py
  tools/ivar/sanitize_bed.py
  tools/ivar/write_amplicon_info_file.py
Labels: virology

#4666 Update pangolin to v4.1.2, pangolin-data to 1.12
  tools/pangolin/pangolin.xml
Labels: virology

#4633 Add data manager for pangolin-data
  data_managers/data_manager_pangolin_data/.shed.yml
  data_managers/data_manager_pangolin_data/data_manager/macros.xml
  data_managers/data_manager_pangolin_data/data_manager/pangolin_data_dm.py
  data_managers/data_manager_pangolin_data/data_manager/pangolin_data_dm.xml
  data_managers/data_manager_pangolin_data/data_manager_conf.xml
  data_managers/data_manager_pangolin_data/test-data/data_compatibility.csv
  data_managers/data_manager_pangolin_data/test-data/pangolin_assignment.loc
  data_managers/data_manager_pangolin_data/test-data/pangolin_constellations.loc
  data_managers/data_manager_pangolin_data/test-data/pangolin_data.loc
  data_managers/data_manager_pangolin_data/tool-data/pangolin_assignment.loc
  data_managers/data_manager_pangolin_data/tool-data/pangolin_constellations.loc
  data_managers/data_manager_pangolin_data/tool-data/pangolin_data.loc
  data_managers/data_manager_pangolin_data/tool_data_table_conf.xml.sample
  data_managers/data_manager_pangolin_data/tool_data_table_conf.xml.test
Labels: virology

#4075 Arriba Gene Fusion tools
  tools/arriba/.shed.yml
  tools/arriba/arriba.xml
  tools/arriba/arriba_draw_fusions.xml
  tools/arriba/arriba_get_filters.xml
  tools/arriba/macros.xml
  tools/arriba/static/images/draw-fusions-example.png
  tools/arriba/test-data/Aligned.out.bam
  tools/arriba/test-data/Aligned.out.bam.bai
  tools/arriba/test-data/Aligned.out.sam
  tools/arriba/test-data/cytobands.tsv
  tools/arriba/test-data/fusions.tsv
  tools/arriba/test-data/genome.fasta.gz
  tools/arriba/test-data/genome.gtf.gz
  tools/arriba/test-data/protein_domains.gff3
  tools/arriba/tool-data/all_fasta.loc.sample
  tools/arriba/tool_data_table_conf.xml.sample
Labels: reviewer needed

#4648 add new Freyja tool
  tools/freyja/.shed.yml
  tools/freyja/freyja_aggregate_plot.xml
  tools/freyja/freyja_boot.xml
  tools/freyja/freyja_demix.xml
  tools/freyja/freyja_variants.xml
  tools/freyja/macros.xml
  tools/freyja/test-data/NC_045512_Hu-1.fasta
  tools/freyja/test-data/abundances.tsv
  tools/freyja/test-data/abundances2.tsv
  tools/freyja/test-data/abundances3.tsv
  tools/freyja/test-data/abundances4.tsv
  tools/freyja/test-data/bunch_of_files.tsv
  tools/freyja/test-data/csv_sample_meta.csv
  tools/freyja/test-data/csv_sample_meta2.csv
  tools/freyja/test-data/depths.tsv
  tools/freyja/test-data/test.bam
  tools/freyja/test-data/test.vcf
  tools/freyja/test-data/times_metadata.csv
  tools/freyja/test-data/variants.tsv
Labels: virology

#4655 Add nextclade data manager
  data_managers/data_manager_nextclade/.shed.yml
  data_managers/data_manager_nextclade/data_manager/nextclade_dm.py
  data_managers/data_manager_nextclade/data_manager/nextclade_dm.xml
  data_managers/data_manager_nextclade/data_manager_conf.xml
  data_managers/data_manager_nextclade/test-data/nextclade.loc
  data_managers/data_manager_nextclade/tool-data/nextclade.loc
  data_managers/data_manager_nextclade/tool_data_table_conf.xml.sample
  data_managers/data_manager_nextclade/tool_data_table_conf.xml.test
Labels: virology
